-- ============================================================
-- TechPulse Chicago — Supabase Database Schema
-- Run this in your Supabase SQL Editor
-- ============================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ============================================================
-- PROFILES (extends Supabase auth.users)
-- ============================================================
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  full_name text,
  avatar_url text,
  bio text,
  role text default 'member' check (role in ('member', 'organizer', 'admin')),
  company text,
  website text,
  linkedin_url text,
  newsletter_subscribed boolean default false,
  newsletter_email text,
  created_at timestamp with time zone default now()
);

-- Auto-create profile on signup
create or replace function handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, username)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url',
    lower(regexp_replace(coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)), '[^a-zA-Z0-9]', '', 'g'))
    || '_' || substring(new.id::text, 1, 6)
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure handle_new_user();

-- ============================================================
-- EVENTS
-- ============================================================
create table if not exists events (
  id uuid primary key default gen_random_uuid(),
  organizer_id uuid references profiles(id) on delete cascade,
  title text not null,
  slug text unique not null,
  description text,
  cover_image_url text,
  category text check (category in ('AI/ML', 'Web Dev', 'DevOps', 'FinOps', 'Startup', 'Networking')),
  tags text[],
  venue_name text,
  venue_address text,
  venue_lat decimal,
  venue_lng decimal,
  is_online boolean default false,
  online_link text,
  start_time timestamptz not null,
  end_time timestamptz not null,
  capacity int,
  is_free boolean default true,
  status text default 'published' check (status in ('draft', 'published', 'cancelled', 'completed')),
  rsvp_count int default 0,
  created_at timestamp with time zone default now()
);

create index if not exists events_start_time_idx on events(start_time);
create index if not exists events_category_idx on events(category);
create index if not exists events_status_idx on events(status);
create index if not exists events_organizer_idx on events(organizer_id);

-- Full-text search
alter table events add column if not exists search_vector tsvector;
create index if not exists events_search_idx on events using gin(search_vector);

create or replace function events_search_update()
returns trigger as $$
begin
  new.search_vector := to_tsvector('english', coalesce(new.title, '') || ' ' || coalesce(new.description, ''));
  return new;
end;
$$ language plpgsql;

create or replace trigger events_search_trigger
  before insert or update on events
  for each row execute procedure events_search_update();

-- ============================================================
-- RSVPs
-- ============================================================
create table if not exists rsvps (
  id uuid primary key default gen_random_uuid(),
  event_id uuid references events(id) on delete cascade,
  user_id uuid references profiles(id) on delete cascade,
  status text default 'going' check (status in ('going', 'waitlist', 'cancelled')),
  checked_in boolean default false,
  checked_in_at timestamptz,
  created_at timestamp with time zone default now(),
  unique(event_id, user_id)
);

create index if not exists rsvps_event_idx on rsvps(event_id);
create index if not exists rsvps_user_idx on rsvps(user_id);

-- ============================================================
-- NEWSLETTER SUBSCRIPTIONS
-- ============================================================
create table if not exists newsletter_subscriptions (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  name text,
  topics text[],
  is_active boolean default true,
  unsubscribe_token uuid default gen_random_uuid() not null,
  subscribed_at timestamp with time zone default now()
);

-- If the table already exists, run this migration in Supabase SQL Editor:
-- alter table newsletter_subscriptions add column if not exists unsubscribe_token uuid default gen_random_uuid() not null;
-- update newsletter_subscriptions set unsubscribe_token = gen_random_uuid() where unsubscribe_token is null;

-- ============================================================
-- NEWSLETTER ISSUES (generated by Claude AI)
-- ============================================================
create table if not exists newsletter_issues (
  id uuid primary key default gen_random_uuid(),
  month_year text not null,
  subject text,
  preview_text text,
  html_body text,
  text_body text,
  sources jsonb,
  metadata jsonb,
  sent_at timestamptz,
  recipient_count int,
  created_at timestamp with time zone default now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

-- Profiles
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Events
alter table events enable row level security;
create policy "Published events are viewable by everyone" on events for select using (status = 'published' or organizer_id = auth.uid());
create policy "Authenticated users can create events" on events for insert with check (auth.uid() = organizer_id);
create policy "Organizers can update own events" on events for update using (auth.uid() = organizer_id);

-- RSVPs
alter table rsvps enable row level security;
create policy "RSVPs are viewable by event organizer and attendee" on rsvps for select using (auth.uid() = user_id or event_id in (select id from events where organizer_id = auth.uid()));
create policy "Authenticated users can RSVP" on rsvps for insert with check (auth.uid() = user_id);
create policy "Users can update own RSVPs" on rsvps for update using (auth.uid() = user_id or event_id in (select id from events where organizer_id = auth.uid()));

-- Newsletter subscriptions (public insert, private read)
alter table newsletter_subscriptions enable row level security;
create policy "Anyone can subscribe" on newsletter_subscriptions for insert with check (true);
create policy "Admins can view subscriptions" on newsletter_subscriptions for select using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- Newsletter issues (public read)
alter table newsletter_issues enable row level security;
create policy "Published issues are viewable by everyone" on newsletter_issues for select using (sent_at is not null);
create policy "Admins can manage issues" on newsletter_issues for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- ============================================================
-- SEED DATA (Sample Categories)
-- ============================================================
insert into newsletter_issues (month_year, subject, preview_text, text_body, sent_at, recipient_count)
values (
  'March 2026',
  'TechPulse FinOps Digest — March 2026',
  'Latest FinOps updates across Snowflake, Databricks, BigQuery, Redshift, and Azure Fabric',
  'Sample issue — run the newsletter generator to create real content.',
  now(),
  0
) on conflict do nothing;
